# Site settings
title: Suministros de Hostelería Maribel
description: "Restauración 2.0"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.png

# Hero
hero: 
    hero_img: hero.jpg
    #hero_title: Suministros de Hostelería Maribel
    #hero_description: Una tienda de cosas

# Contact form
api_token: 3125ae7107ece34909556b17238fb2b1

# Contact info
contact:
    phone: 952 82 26 23
    #emergency: 931 53 234
    email: info@hosteleriamaribel.com
    address: Avenida Arias de Velasco, 14, 29601 Marbella (Málaga)

# Opening hours
monday_friday: 9:30 – 14:00 / 16:30 – 20:30
saturday: 9:30 – 14:00
sunday: Cerrado

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Avenida Arias de Velasco, 20, Marbella
    address_details: svg/min/logo.png

# Social settings
facebook: http://facebook.com/hosteleriamaribel
twitter: 
instagram: 
youtube: 
skype: 
feed: 

# Footer
copyright: © 2016 Suministros de hostelería Maribel - Todos los derechos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
